# DXP
ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: ImplementationSpecific

resources:
  limits:
    cpu: "4000m"
    memory: "12Gi"
  requests:
    cpu: "2000m"
    memory: "4Gi"
storage: 10Gi

startupProbe:
  httpGet:
    path: /c/portal/robots
    port: http
  failureThreshold: 60
  initialDelaySeconds: 20
  periodSeconds: 5

# Database
database:
  internal:
    resources:
      limits:
        cpu: "2000m"
        memory: "2Gi"
      requests:
        cpu: "1000m"
        memory: "1Gi"
    storage: 1Gi

# Object Storage
objectstorage:
  internal:
    ingress:
      enabled: false
      limits:
        cpu: "2000m"
        memory: "2Gi"
      requests:
        cpu: "1000m"
        memory: "1Gi"
    storage: 1Gi

# Search
search:
  internal:
    resources:
      limits:
        cpu: "2000m"
        memory: "2Gi"
      requests:
        cpu: "1000m"
        memory: "1Gi"
    storage: 1Gi
