ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: ImplementationSpecific

resources:
  limits:
    cpu: "4000m"
    memory: "12Gi"
  requests:
    cpu: "2000m"
    memory: "4Gi"
storage: 10Gi

objectstorage:
  internal:
    ingress:
      enabled: false

startupProbe:
  httpGet:
    path: /c/portal/robots
    port: http
  failureThreshold: 60
  initialDelaySeconds: 20
  periodSeconds: 5
